"""auto

Revision ID: 20250910210649
Revises: 20250910210328
Create Date: 2025-09-10 21:06:49.618266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250910210649'
down_revision: Union[str, Sequence[str], None] = '20250910210328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonds', 'maturity_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonds', 'maturity_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
