"""auto

Revision ID: 20250910205038
Revises: 20250910203753
Create Date: 2025-09-10 20:50:39.265089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250910205038'
down_revision: Union[str, Sequence[str], None] = '20250910203753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonds', sa.Column('secid', sa.String(), nullable=False))
    op.add_column('bonds', sa.Column('emitent', sa.String(), nullable=False))
    op.add_column('bonds', sa.Column('market', sa.String(), nullable=False))
    op.add_column('bonds', sa.Column('coupon', sa.Float(), nullable=False))
    op.add_column('bonds', sa.Column('maturity_date', sa.Date(), nullable=False))
    op.add_column('bonds', sa.Column('rating', sa.String(), nullable=True))
    op.alter_column('bonds', 'isin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bonds', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_bonds_id'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_isin'), table_name='bonds')
    op.create_index(op.f('ix_bonds_isin'), 'bonds', ['isin'], unique=False)
    op.create_index(op.f('ix_bonds_emitent'), 'bonds', ['emitent'], unique=False)
    op.create_index(op.f('ix_bonds_market'), 'bonds', ['market'], unique=False)
    op.create_index(op.f('ix_bonds_maturity_date'), 'bonds', ['maturity_date'], unique=False)
    op.create_index(op.f('ix_bonds_rating'), 'bonds', ['rating'], unique=False)
    op.create_index(op.f('ix_bonds_secid'), 'bonds', ['secid'], unique=True)
    op.drop_column('bonds', 'issuer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonds', sa.Column('issuer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bonds_secid'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_rating'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_maturity_date'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_market'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_emitent'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_isin'), table_name='bonds')
    op.create_index(op.f('ix_bonds_isin'), 'bonds', ['isin'], unique=True)
    op.create_index(op.f('ix_bonds_id'), 'bonds', ['id'], unique=False)
    op.alter_column('bonds', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bonds', 'isin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('bonds', 'rating')
    op.drop_column('bonds', 'maturity_date')
    op.drop_column('bonds', 'coupon')
    op.drop_column('bonds', 'market')
    op.drop_column('bonds', 'emitent')
    op.drop_column('bonds', 'secid')
    # ### end Alembic commands ###
