"""auto

Revision ID: 20250910213155
Revises: 20250910210649
Create Date: 2025-09-10 21:31:55.825120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250910213155'
down_revision: Union[str, Sequence[str], None] = '20250910210649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bond_prices_id'), table_name='bond_prices')
    op.drop_table('bond_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bond_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bond_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], name=op.f('bond_prices_bond_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bond_prices_pkey'))
    )
    op.create_index(op.f('ix_bond_prices_id'), 'bond_prices', ['id'], unique=False)
    # ### end Alembic commands ###
