"""auto

Revision ID: 20250910110425
Revises: 20250909190444
Create Date: 2025-09-10 11:04:26.087437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250910110425'
down_revision: Union[str, Sequence[str], None] = '20250909190444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bond_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bond_prices_id'), 'bond_prices', ['id'], unique=False)
    op.add_column('bonds', sa.Column('isin', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('issuer', sa.String(), nullable=True))
    op.drop_index(op.f('ix_bonds_ticker'), table_name='bonds')
    op.create_index(op.f('ix_bonds_isin'), 'bonds', ['isin'], unique=True)
    op.drop_column('bonds', 'price')
    op.drop_column('bonds', 'ticker')
    op.drop_column('bonds', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonds', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bonds', sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bonds', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bonds_isin'), table_name='bonds')
    op.create_index(op.f('ix_bonds_ticker'), 'bonds', ['ticker'], unique=True)
    op.drop_column('bonds', 'issuer')
    op.drop_column('bonds', 'isin')
    op.drop_index(op.f('ix_bond_prices_id'), table_name='bond_prices')
    op.drop_table('bond_prices')
    # ### end Alembic commands ###
