"""add coupon_display to bonds

Revision ID: cf3ecec52402
Revises: 20250911114745
Create Date: 2025-09-18 08:49:40.272609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3ecec52402'
down_revision: Union[str, Sequence[str], None] = '20250911114745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonds', sa.Column('coupon_display', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('coupon_type', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('ytm', sa.Float(), nullable=True))
    op.add_column('bonds', sa.Column('ytm_date', sa.Date(), nullable=True))
    op.add_column('bonds', sa.Column('last_price', sa.Float(), nullable=True))
    op.add_column('bonds', sa.Column('amortization', sa.Boolean(), nullable=True))
    op.add_column('bonds', sa.Column('offer_date', sa.Date(), nullable=True))
    op.add_column('bonds', sa.Column('akra_rating', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('akra_forecast', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('raexpert_rating', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('raexpert_forecast', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('nkr_rating', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('nkr_forecast', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('currency_symbol', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('bonds', 'secid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bonds', 'isin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bonds', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bonds', 'emitent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bonds', 'market',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bonds', 'coupon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_bonds_isin'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_rating'), table_name='bonds')
    op.drop_column('bonds', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonds', sa.Column('rating', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_bonds_rating'), 'bonds', ['rating'], unique=False)
    op.create_index(op.f('ix_bonds_isin'), 'bonds', ['isin'], unique=False)
    op.alter_column('bonds', 'coupon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('bonds', 'market',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bonds', 'emitent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bonds', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bonds', 'isin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bonds', 'secid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bonds', 'updated_at')
    op.drop_column('bonds', 'currency_symbol')
    op.drop_column('bonds', 'currency')
    op.drop_column('bonds', 'nkr_forecast')
    op.drop_column('bonds', 'nkr_rating')
    op.drop_column('bonds', 'raexpert_forecast')
    op.drop_column('bonds', 'raexpert_rating')
    op.drop_column('bonds', 'akra_forecast')
    op.drop_column('bonds', 'akra_rating')
    op.drop_column('bonds', 'offer_date')
    op.drop_column('bonds', 'amortization')
    op.drop_column('bonds', 'last_price')
    op.drop_column('bonds', 'ytm_date')
    op.drop_column('bonds', 'ytm')
    op.drop_column('bonds', 'coupon_type')
    op.drop_column('bonds', 'coupon_display')
    # ### end Alembic commands ###
